"""
RequestLog — append-only usage / analytics ledger.

One row per call, with per-key attribution: which gateway key, the requested
model, and the exact deployment + provider key that answered. That is what lets
you see per-key burn and spot an exhausted key.

Reference FKs are ON DELETE SET NULL so history survives a key or model being
removed; only user_id cascades (deleting a user deletes their history).

`total_tokens` is GENERATED by the DB from its parts — it cannot be logged wrong.

NO is_fallback COLUMN. It used to mean "did we leave the primary?", but there is
no primary any more (no ordering anywhere, by design), so the question is
unanswerable. Which provider answered is already recorded in provider_id.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Column, BigInteger, Integer, String, Text, DateTime, Numeric, ForeignKey,
    Computed,
)

from app.core.database import Base, BigIntPK


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class RequestLog(Base):
    __tablename__ = "request_logs"

    id = Column(BigIntPK, primary_key=True, autoincrement=True)
    user_id = Column(
        BigInteger, ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    gateway_api_key_id = Column(
        BigInteger, ForeignKey("gateway_api_keys.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )

    requested_model = Column(String, nullable=False)   # bare family name the client sent
    answered_deploy_id = Column(
        BigInteger, ForeignKey("deployments.id", ondelete="SET NULL"), nullable=True,
    )
    provider_model_id = Column(
        BigInteger, ForeignKey("provider_models.id", ondelete="SET NULL"), nullable=True,
    )
    provider_key_id = Column(
        BigInteger, ForeignKey("provider_keys.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    provider_id = Column(
        BigInteger, ForeignKey("providers.id", ondelete="SET NULL"), nullable=True,
    )

    prompt_tokens = Column(Integer, nullable=False, default=0)
    completion_tokens = Column(Integer, nullable=False, default=0)
    # DB-generated: prompt + completion. Read-only from Python.
    total_tokens = Column(
        Integer, Computed("prompt_tokens + completion_tokens", persisted=True),
    )

    cost = Column(Numeric(12, 6), nullable=False, default=0)
    latency_ms = Column(Integer, nullable=True)
    status_code = Column(Integer, nullable=False, default=200)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=_utcnow, index=True)

    # ── combo attribution ───────────────────────────────────────────────────
    # NULL for a direct model call. Set when the request was addressed to a combo
    # (models/combo.py), which is otherwise invisible here: `requested_model`
    # holds the combo's name but nothing says whether it WAS a combo, and the
    # answering deployment says nothing about which step produced it.
    #
    # combo_attempt is the 1-based position of the target that ANSWERED, so
    # `> 1` means the chain fell back — the one number the combo dashboard needs
    # and the only one that cannot be reconstructed after the fact.
    combo_name = Column(String(120), nullable=True)
    combo_attempt = Column(Integer, nullable=True)

    def __repr__(self) -> str:
        return f"<RequestLog id={self.id} {self.requested_model!r} {self.status_code}>"
